---
title: "git_01"
author: "Kayla Yost"
date: "March 18, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
In winter, when the fields are white,  
I sing this song for your delight.  
In Spring, when woods are getting green,  
I'll try and tell you what I mean.  
In Summer, when the days are long,  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
I staid the night for shelter at a farm  
Behind the mountains, with a mother and son,  
Two old-believers. They did all the talking.  
  
MOTHER Folks think a witch who has familiar spirits  
She could call up to pass a winter evening,  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright--  
And this was odd, because it was  
The middle of the night.  
  
The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done--  
"It's very rude of him," she said,  
"To come and spoil the fun!"  


## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Do you like green eggs and ham?  
  
I do not like them, Sam-I-am.  
I do not like green eggs and ham!  
  
Would you like them here or there?  
  
I would not like them here or there.  
I would not like them anywhere.  
  
I do so like green eggs and ham!  
Thank you! Thank you,  
Sam-I-am!  
